package xlsx

var (
	partNameString         = []byte("PartName")
	contentTypeString      = []byte("ContentType")
	overrideString         = []byte("Override")
	sheetString            = []byte("sheet")
	sheetNameString        = []byte("name")
	sheetIDString          = []byte("sheetId")
	sstString              = []byte("sst")
	tString                = []byte("t")
	sString                = []byte("s")
	rString                = []byte("r")
	cString                = []byte("c")
	vString                = []byte("v")
	isString               = []byte("is")
	rowString              = []byte("row")
	inlineString           = []byte("inlineStr")
	workSheetURIString     = []byte("application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml")
	sharedStringsURIString = []byte("application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml")
)
